// vuejs-3-example/src/views/Dashboard.vue
<template>
  <AnimeForm @form-submit="onFormSubmit($event)" />

  <div class="mt-12 mb-3">Total Selected Data: {{ animeStore.getStoredAnime.length }}</div>

  <div class="flex flex-col gap-4">
    <GeneralCard
      v-for="data in animeStore.getStoredAnime"
      :key="data.selectedAnime.popularity"
      :title="data.selectedAnime.title"
      :show-button-delete="true"
      :show-button-details="true"
      @details-clicked="onDetails(data)"
      @delete-clicked="onDelete(data)"
    >
      <AnimeDetails :anime-data="data" />
    </GeneralCard>
  </div>

  <footer class="max-h-14"></footer>
</template>

<script setup lang="ts">
import { useRouter } from "vue-router";
import AnimeDetails from "../components/anime/AnimeDetails.vue";
import AnimeForm from "../components/anime/AnimeForm.vue";
import GeneralCard from "../components/shared/GeneralCard.vue";
import { AnimeTypeStore, useAnimeStore } from "../store/anime.store";

const animeStore = useAnimeStore();
const router = useRouter();

const onFormSubmit = (value: AnimeTypeStore) => {
  animeStore.saveAnimeToStore(value);
};

function onDetails(data: AnimeTypeStore) {
  router.push(`/anime/${data.selectedAnime.mal_id}`);
}

const onDelete = (data: AnimeTypeStore) => {
  animeStore.deleteAnimeFromStore(data);
};
</script>

<style scoped></style>

// angular-example/src/app/views/dashboard.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { Router } from '@angular/router';
import { AnimeDetailsComponent } from '../components/anime/anime-details.component';
import { AnimeFormComponent } from '../components/anime/anime-form.component';
import { GeneralCardComponent } from '../components/shared/general-card.component';
import { AnimeService, AnimeTypeStore } from '../services/anime.service';

@Component({
	selector: 'app-dashboard',
	standalone: true,
	imports: [CommonModule, AnimeFormComponent, GeneralCardComponent, AnimeDetailsComponent],
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		<section>
			<app-anime-form (formSubmit)="onFormSubmit($event)"></app-anime-form>

			<div class="mt-12 mb-3">Total Selected Data: {{ (animeStore.storedAnimeObs$ | async)?.length }}</div>

			<div class="flex flex-col gap-4">
				<app-general-card
					*ngFor="let data of animeStore.storedAnimeObs$ | async"
					[title]="data.selectedAnime.title"
					[showButtonDelete]="true"
					[showButtonDetails]="true"
					(detailsClicked)="onDetails(data)"
					(deleteClicked)="onDelete(data)"
				>
					<app-anime-details [animeData]="data"></app-anime-details>
				</app-general-card>
			</div>

			<footer class="h-16"></footer>
		</section>
	`,
})
export class DashboardComponent {
	animeStore = inject(AnimeService);
	router = inject(Router);

	onFormSubmit(value: AnimeTypeStore) {
		this.animeStore.saveAnimeToStore(value);
	}

	onDetails(data: AnimeTypeStore) {
		this.router.navigate([`/anime/${data.selectedAnime.mal_id}`]);
	}

	onDelete(data: AnimeTypeStore) {
		this.animeStore.deleteAnimeFromStore(data);
	}
}
