// angular-example/src/app/components/views/main.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { RouterModule } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
	selector: 'app-main',
	standalone: true,
	imports: [CommonModule, RouterModule],
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		<nav class="flex items-center justify-between w-full gap-4 p-4 mt-2 bg-green-700">
			<a routerLink="/dashboard" class="link"> Dashboard </a>
			<a routerLink="/login" class="link" (click)="onLogOut()"> Logout </a>
		</nav>

		<div class="mt-20 text-xl text-center">
			Welcome: {{ (authenticationStore.authenticatedUserObs$ | async)?.name }}
		</div>

		<main class="w-full max-w-[840px] mx-auto mt-20 px-3 sm:px-6">
			<router-outlet></router-outlet>
		</main>
	`,
})
export class MainComponent {
	authenticationStore = inject(AuthService);

	onLogOut() {
		this.authenticationStore.removeAuthenticatedUser();
	}
}

// vuejs-3-example/src/views/Main.vue
<template>
  <nav class="flex items-center justify-between w-full gap-4 p-4 bg-green-700">
    <router-link to="/dashboard" class="link"> Dashboard </router-link>
    <router-link to="/login" class="link"> Logout </router-link>
  </nav>

  <main class="w-full max-w-[840px] mx-auto mt-20 px-3 sm:px-6">
    <router-view />
  </main>
</template>

<script setup lang="ts"></script>

<style scoped>
.link {
  @apply px-5 py-2 text-white hover:bg-green-400 rounded-lg text-lg cursor-pointer duration-300 transition-all;
}
</style>
