// angular-example/src/app/components/shared/banner.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { HideAfterDirective } from '../../directives/hide-after.directive';

@Component({
	selector: 'app-banner',
	standalone: true,
	imports: [CommonModule, HideAfterDirective],
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		<div
			*hideAfter="bannerTime as time; let counter = counter"
			class="w-full p-4 text-xl text-center text-white bg-red-500"
		>
			Remaining time for banner: {{ counter }}
		</div>
	`,
})
export class BannerComponent {
	@Input() bannerTime: number = 6;
}

// vuejs-3-example/src/components/shared/Banner.vue
<template>
  <div>
    <div v-sticky="'top'" class="w-full">This is a heading</div>
    <div
      v-display-for-time-2="{ seconds: bannerTime }"
      class="w-full p-4 text-xl text-center text-white bg-red-500"
      @remainingTime="bannerTime--"
    >
      Remaining time for banner: {{ bannerTime }}
    </div>
  </div>
</template>

<script setup lang="ts">
const bannerTime = ref(6);
</script>

<style scoped></style>
