// angular-example/src/app/components/shared/comp-shark.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, OnInit } from '@angular/core';
import { delay, map, of } from 'rxjs';

@Component({
	selector: 'app-comp-shark',
	standalone: true,
	imports: [CommonModule],
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		<ng-container *ngIf="image$ | async as image; else loader">
			<img [src]="image" class="w-[400px] h-[300px]" />
		</ng-container>

		<ng-template #loader>
			<div class="w-[400px] h-[300px] animate-pulse bg-gray-500 p-2"></div>
		</ng-template>
	`,
})
export class CompSharkComponent implements OnInit {
	readonly url = 'https://cdn.britannica.com/79/65379-050-5CF52BAC/Shortfin-mako-shark-seas.jpg';

	image$ = of([]).pipe(
		delay(2500),
		map(() => this.url)
	);

	ngOnInit(): void {
		console.log('[CompSharkComponent] ngOnInit');
	}
}

// vuejs-3-example/src/components/shared/CompShark.vue
<template>
  <div v-if="isLoading" class="w-[400px] h-[300px] animate-pulse bg-gray-500 p-2"></div>
  <div v-else-if="error">Failed</div>
  <img v-else :src="imageOptions.src" class="w-[400px] h-[300px]" />
</template>

<script setup lang="ts">
import { useImage } from "@vueuse/core";

onMounted(() => {
  console.log("[Shark] component on Mounted");
});

const imageOptions = ref({ src: "https://cdn.britannica.com/79/65379-050-5CF52BAC/Shortfin-mako-shark-seas.jpg" });
const { isLoading, error } = useImage(imageOptions, { delay: 2500 });
</script>

<style scoped></style>
