// angular-example/src/app/components/anime/anime-form-search.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, effect, inject, signal } from '@angular/core';
import { ControlValueAccessor, FormsModule, NG_VALUE_ACCESSOR } from '@angular/forms';
import { useValidator } from '../../composable/useValidator';
import { AnimeData } from '../../models/api-anime-data.model';
import { AnimeService } from '../../services/anime.service';

@Component({
	selector: 'app-anime-form-search',
	standalone: true,
	imports: [CommonModule, FormsModule],
	changeDetection: ChangeDetectionStrategy.OnPush,
	providers: [
		{
			provide: NG_VALUE_ACCESSOR,
			useExisting: AnimeFormSearchComponent,
			multi: true,
		},
	],
	template: `
		<div class="relative flex flex-col">
			Typing: {{ searchRef() }}

			<!-- search text input  -->
			<input
				[value]="searchRef()"
				(input)="saveSearchValue($event)"
				type="text"
				name="searchRef"
				placeholder="Search.."
				(keypress)="onInputKeyDown()"
			/>

			<!-- errors in search -->
			<div *ngIf="errors().selectedAnimeError.errors.length > 0" class="flex flex-col mb-2">
				<span *ngFor="let err of errors().selectedAnimeError.errors" class="text-red-400">
					{{ err }}
				</span>
			</div>

			<!-- results  -->
			<div *ngIf="!searchLoadingRef() && !searchSelectedRef() && searchRef().length > 3" class="flex flex-col w-full">
				<button
					*ngFor="let data of animeService.getLoadedAnime()"
					type="button"
					class="g-select-value"
					(click)="onClick(data)"
				>
					{{ data.title }}
				</button>
			</div>
			<div *ngIf="searchLoadingRef() && searchRef().length > 3">Loading ...</div>
		</div>
	`,
})
export class AnimeFormSearchComponent implements ControlValueAccessor {
	searchRef = signal('');
	// remember the selected value
	searchSelectedRef = signal(false);
	// mark to true to show loading screen
	searchLoadingRef = signal(false);

	animeService = inject(AnimeService);

	onChange: (value: AnimeData) => void = () => {};
	onTouched = () => {};

	effectRef = effect(
		() => {
			//console.log('effect', this.searchSelectedRef());
			// fetching anime data from api, don't fetch if I already selected
			if (this.searchRef().length > 3 && !this.searchSelectedRef()) {
				console.log('eefect running');
				this.searchSelectedRef.set(false);
				this.searchLoadingRef.set(false);
				this.animeService.fetchAnime(this.searchRef());
			}
		},
		{ allowSignalWrites: true }
	);

	errors = computed(() => {
		const modelValue = this.searchRef();
		//	console.log('running computed', modelValue);

		const selectedAnimeError = useValidator({
			value: modelValue,
			type: 'text',
			validations: {
				required: {
					value: true,
					message: 'Value is required',
				},
				min: {
					value: 3,
					message: 'Value must be at least 3 characters',
				},
			},
		});

		return { selectedAnimeError };
	});

	saveSearchValue(event: Event) {
		const value = (event.target as HTMLInputElement).value;
		this.searchRef.set(value);
	}

	onInputKeyDown() {
		console.log('onInputKeyDown');
		this.searchLoadingRef.set(true);
		this.searchSelectedRef.set(false);
	}

	onClick(data: AnimeData) {
		// update search with whole value
		this.searchRef.set(data.title);

		// set selected to true
		this.searchSelectedRef.set(true);

		// set loading to false
		this.searchLoadingRef.set(false);

		// emit event to parent
		this.onChange(data);
	}

	/*
    parent component adds value to child
  */
	writeValue(animeData?: AnimeData): void {
		console.log('writeValue', animeData);
		this.searchRef.set(animeData?.title ?? '');
	}

	/*
    method to notify parent that the value (disabled state) has been changed
  */
	registerOnChange(fn: AnimeFormSearchComponent['onChange']): void {
		this.onChange = fn;
	}

	/*
    method to notify parent that form control has been touched
  */
	registerOnTouched(fn: AnimeFormSearchComponent['onTouched']): void {
		this.onTouched = fn;
	}
}

// vuejs-3-example/src/components/anime/AnimeFormSearch.vue
<template>
  <div class="relative flex flex-col">
    <!-- search text input -->
    <input v-model="searchRef" type="text" placeholder="Search.." @keydown="onInputKeyDown" />

    <!-- errors in search -->
    <div v-if="errors.selectedAnimeError.errors.length > 0" class="flex flex-col mb-2">
      <span v-for="(err, index) of errors.selectedAnimeError.errors" :key="index" class="text-red-400">{{ err }}</span>
    </div>

    <!-- results -->
    <div v-if="!searchLoadingRef && !searchSelectedRef && searchRef.length > 3" class="flex flex-col w-full">
      <button
        v-for="data in animeStore.getLoadedAnime"
        :key="data.title"
        type="button"
        class="g-select-value"
        @click="onClick(data)"
      >
        {{ data.title }}
      </button>
    </div>
    <div v-else-if="searchLoadingRef && searchRef.length > 3">Loading ...</div>
  </div>
</template>

<script setup lang="ts">
import { watchDebounced } from "@vueuse/core";
import { PropType, computed, ref, watchEffect } from "vue";
import { useValidator } from "../../composable/useValidator";
import { AnimeData } from "../../models/api-anime-data.model";
import { useAnimeStore } from "../../store/anime.store";

const animeStore = useAnimeStore();

const props = defineProps({
  modelValue: {
    type: Object as PropType<AnimeData | null>,
    required: false,
    default: null
  }
});

const emit = defineEmits<{
  (e: "update:modelValue", value: AnimeData): void;
}>();

const searchRef = ref<string>("");
// remember the selected value
const searchSelectedRef = ref<boolean>(false);
// mark to true to show loading screen
const searchLoadingRef = ref<boolean>(false);

watchEffect(() => {
  // when props change from parent, put this value in input
  // console.log("Parent changing Anime Form search prop", props.modelValue);
  searchRef.value = props.modelValue?.title ?? "";
});

// wait some time before firing api call
watchDebounced(
  searchRef,
  () => {
    // fetching anime data from api, don't fetch if I already selected
    if (searchRef.value.length > 3 && !searchSelectedRef.value) {
      searchSelectedRef.value = false;
      searchLoadingRef.value = false;
      animeStore.fetchAnime(searchRef.value);
    }
  },
  { debounce: 1000 }
);

// error validation for searchable text input
const errors = computed(() => {
  const modelValue = searchRef.value;

  const selectedAnimeError = useValidator({
    value: modelValue,
    type: "text",
    validations: {
      required: {
        value: true,
        message: "Value is required"
      },
      min: {
        value: 3,
        message: "Value must be at least 3 characters"
      }
    }
  });

  return { selectedAnimeError };
});

const onClick = (data: AnimeData) => {
  // update search with whole value
  searchRef.value = data.title;

  // set selected to true
  searchSelectedRef.value = true;

  // set loading to false
  searchLoadingRef.value = false;

  // emit event to parent
  emit("update:modelValue", data);
};

const onInputKeyDown = () => {
  console.log("onInputKeyDown");
  searchLoadingRef.value = true;
  searchSelectedRef.value = false;
};
</script>

<style scoped></style>
